### ISSUE TITLE
API / Asynchronous objects Issue with IIS7

### ISSUE THREAD

**Issue by Jason2144** [blueriver/MuraBootstrap3Bundle#1]
Content objects in the bundle are having an issue when loaded Asynchronously with IIS.

For example, in the news section:

domain.com/news/not-all-wine-comes-from-california-after-all/

When the comments section is loaded, IIS is throwing a 500 error (not a coldfusion related error)

![5-10-2016 12-43-47 pm](https://cloud.githubusercontent.com/assets/14875145/15154705/f6303c2e-16ac-11e6-91cb-66a92f4e16d5.jpg)

The URL mura is trying to fetch is:

/index.cfm/_api/json/v1/Bootstrap3/?method=processAsyncObject&approvedcomment=&spamcomment=&deletecomment=&async=true&render=server&=&css=&objectname=**%3Ci%20class=%22mi-cog%22%3E%3C/i%3E%20**System&instanceid=203848E7-BDEE-4433-A5B8CF4642DA0DC4&objectid=1491C9FF-9022-4C92-8310E0988A32362B&object=comments&siteid=Bootstrap3&contentid=9F32E110-CD4B-4C3B-AD3A1F9E8417B941&contenthistid=40E025C0-DE58-4A05-B60D0D341ABA4F83

The  portion of URL bolded above is causing an issue with IIS. If you take out the bolded part, the url loads up correctly and JSON is returned.

I see the bolded text in the tcontentobjects table, but removing them doesn't seem to remove them from the api call as they are still present in the URL, so I think I may be missing where these are called from.

I noticed in the bundle wddx_rstcontent.xml and wddx_rstcontentobjects.xml these are also present

**Comment by stevewithington** [comment]
@Jason2144 could you please confirm you're attempting to deploy on Mura 7 and not Mura 6.2?

**Comment by stevewithington** [comment]
@Jason2144 also, could you please click the link in your debugger so we can see the actual error in it's entirety?

**Comment by Jason2144** [comment]
Steve, Yes, Mura 7 for sure. Screen shot below. I just deployed the bundle again after my initial post and have the same results. I  took a screenshot of the tcontentobjects table as well. Error is also attached per your request, although it won't tell you much aside from telling me to turn on detailed errors. I am 100% certain i have detailed errors enabled in IIS, but IIS refuses to show the actual error. Log files aren't showing anything useful either.

Should that icon markup be part of the object name? Or is that in error?

![capture](https://cloud.githubusercontent.com/assets/14875145/15155934/c8f6f5c6-16b2-11e6-8e33-8e0ffa91d3c7.JPG)

![capture2](https://cloud.githubusercontent.com/assets/14875145/15155935/c8f710d8-16b2-11e6-8aef-0f796e59655b.JPG)

![5-10-2016 1-28-56 pm](https://cloud.githubusercontent.com/assets/14875145/15156034/355aa744-16b3-11e6-90a1-215f5ca3bb72.jpg)

**Comment by mattlevine** [comment]
What do you see when you go to  http://yourdomain.com/index.cfm/_api/json/v1/default  ?

Also can you enable custom errors in your web.config to get more information?

-Matt

**Comment by Jason2144** [comment]
It returns a string of JSON

`{"data":{"entityname":"entityname","links":{"self":"http://example.com/index.cfm/_api/json/v1/default"},"items":[{"entityname":"category","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/category"}},{"entityname":"changeset","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/changeset"}},{"entityname":"changesetCategoryAssignment","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/changesetCategoryAssignment"}},{"entityname":"comment","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/comment"}},{"entityname":"content","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/content"}},{"entityname":"contentCategoryAssign","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/contentCategoryAssign"}},{"entityname":"feed","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/feed"}},{"entityname":"file","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/file"}},{"entityname":"fileMetaData","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/fileMetaData"}},{"entityname":"site","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/site"}},{"entityname":"stats","links":{"endpoint":"http://example.com/index.cfm/_api/json/v1/default/stats"}}]},"params":{"entityname":"entityname","siteid":"default"},"method":"findAll","apiversion":"v1"}`

Detailed errors are enabled in the web.config, but IIS still just shows that generic message. Like I said, if you take out the html markup out of the url, JSON is correctly returned.

Web.config shows its enabled. Rebooted just to besure it picked everything up.
<httpErrors errorMode="Detailed" />

**Comment by mattlevine** [comment]
Is there a log on you server that has more information?

**Comment by mattlevine** [comment]
The error is probably in your CF exception log.

**Comment by Jason2144** [comment]
Nothing in CFLogs. Doesn't appear to be a coldfusion error, but I finally got IIS to display the actual error. Looks like IIS is indeed blocking the request becuase of the html markup in the url.

![5-10-2016 9-35-40 pm](https://cloud.githubusercontent.com/assets/14875145/15167486/3ad2d1a8-16f7-11e6-9e2b-ade358c37b37.jpg)

**Comment by mattlevine** [comment]
That actually give me some decent info. I'll post back here when I have something to test.  Hopefully in the next day or two.

**Comment by Jason2144** [comment]
I was able to bypass this security check by adding the code below to my web.config, but I would not recommended doing this in a production environment. 

```
<system.web>
    <httpRuntime requestPathInvalidCharacters="<,>" requestValidationMode="2.0" />
    <pages validateRequest="false" />
</system.web>
```

Once I added the above, everything seems to be functioning normally.

**Comment by stevewithington** [comment]
@Jason2144 closing this ticket, since your issue appears to have been resolved. Thanks!
